# BAG OF WORDS




In [1]:
!pip install scikit-learn

In [2]:
from sklearn.feature_extraction.text import CountVectorizer

In [3]:
import pandas as pd
df= pd.read_csv("data/nlp.csv",index_col=0)
df.head()

Text
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...
3  9. Baidu Research: Çin'in önde gelen arama mot...
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...

In [4]:

import on_islem

In [5]:
df["Text_2"]=df["Text"].apply(on_islem.pre_processing)
df["Text_2"]=df["Text_2"].apply(on_islem.remove_space)
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [6]:
#boş liste kontrolü
df[df["Text_2"].str[0].isnull()]


Text Text_2
194  #hesaplamalısosyalbilimler #computationalsocia...     []
544  @barolar #ImageRecognition #SınırlıHafıza #Lim...     []

In [7]:
df_index=df[df["Text_2"].str[0].isnull()].index
df=df.drop(df_index)
df=df.reset_index()
del df["index"]
df[df["Text_2"].str[0].isnull()]


Empty DataFrame
Columns: [Text, Text_2]
Index: []

In [8]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2  
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  
1  [veri, analiz, edin, chatgptyi, kullanarak, do...  
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...  
3  [baidu, research, çin, ön, gele, ara, motor, b...  
4  [microsoft, ai, microsoft, yapay, zeka, teknol...

In [9]:
df["Text_2"]

0      [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...
1      [veri, analiz, edin, chatgptyi, kullanarak, do...
2      [öncelik, yapay, zeka, olduğunu, iç, önemli, o...
3      [baidu, research, çin, ön, gele, ara, motor, b...
4      [microsoft, ai, microsoft, yapay, zeka, teknol...
                             ...                        
851    [doğal, dil, işle, alan, yük, lisansdoktor, ya...
852                                   [dogal, dil, isle]
853    [ver, madencilik, doğal, dil, işle, uygulamas,...
854    [doğal, dil, işleme, il, ilgil, deney, ola, ya...
855    [hafta, öğrencilik, hayat, kaldık, yer, deva, ...
Name: Text_2, Length: 856, dtype: object

In [10]:
df["Text_3"]=[' '.join(w for w in item) for item in df["Text_2"]]
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                                 [dogal, dil, isle]   
853  [ver, madencilik, doğal, dil, işle, uygulamas,...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3  
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  
1    veri analiz edin chatgptyi kullanarak doğal di...  
2    öncelik yapay zeka olduğunu iç önemli olduk kı...  
3    baidu research çin ön gele ara motor baidun ar...  
4    microsoft ai microsoft yapay zeka teknoloji od...  
..                                                 ...  
851  doğal dil işle alan yük lisansdoktor yapa danı...  
852                                     dogal dil isle  
853  ver madencilik doğal dil işle uygulamas httpww...  
854  doğal dil işleme il ilgil deney ola yazılımcı ...  
855  hafta öğrencilik hayat kaldık yer deva ediyoru...  

[856 rows x 3 columns]

In [11]:
vectorizer=CountVectorizer()
X=vectorizer.fit_transform(df["Text_3"].tolist())
X

<856x5325 sparse matrix of type '<class 'numpy.int64'>'
	with 17513 stored elements in Compressed Sparse Row format>

In [12]:
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [13]:
X[0]

<1x5325 sparse matrix of type '<class 'numpy.int64'>'
	with 29 stored elements in Compressed Sparse Row format>

In [14]:
df["Text_4"]=X.toarray().tolist()
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4  
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...

In [15]:
set(X.toarray()[0].tolist())


{0, 1, 2, 3, 4}

In [16]:
vectorizer.vocabulary_.keys()

dict_keys(['yapay', 'zeka', 'nedir', 'işe', 'yarar', 'yz', 'bilgisayar', 'diğer', 'cihazların', 'in', 'benzer', 'şekil', 'düşünmesini', 'öğrenmesini', 'karar', 'verme', 'proble', 'çözme', 'sağlaya', 'bil', 'dalıdır', 'teknolojisi', 'doğal', 'dil', 'işleme', 'ses', 'tanıma', 'gör', 'httpstcondhigodfe', 'veri', 'analiz', 'edin', 'chatgptyi', 'kullanarak', 'işle', 'nlp', 'yetenek', 'faydalanarak', 'en', 'sa', 'ürün', 'nelerdir', 'müşter', 'tutma', 'ora', 'gip', 'soru', 'sor', 'chatgpt', 'dayal', 'içgörü', 'sağlasın', 'öncelik', 'olduğunu', 'iç', 'önemli', 'olduk', 'kısaç', 'inceleyelim', 'ai', 'kendi', 'verecek', 'programla', 'sürecidir', 'bu', 'mak', 'öğrenimi', 'tahm', 'analitik', 'çeşitli', 'yönte', 'yapılabilir', 'baidu', 'research', 'çin', 'ön', 'gele', 'ara', 'motor', 'baidun', 'araştırma', 'ola', 'otono', 'araç', 'teknoloji', 'üzer', 'çalışmaktadır', 'twitter', 'hesapları', 'microsoft', 'odaklana', 'robotik', 'sistem', 'openai', 'dünya', 'şirket', 'geliş', 'otomatik', 'öğrenme', 'o

# TF-IDF

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer

vectorizer = TfidfVectorizer()
X= vectorizer.fit_transform(df["Text_3"].tolist())


In [18]:
print(X.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [19]:
set(X.toarray()[0])

{0.0,
 0.034167940760755786,
 0.03588892902583563,
 0.11986838199881836,
 0.12526568480240194,
 0.12592448007034227,
 0.1453590567670003,
 0.14919987400572668,
 0.1505877113952311,
 0.152037250329445,
 0.16242178977861585,
 0.16919275511529722,
 0.17180288831277857,
 0.18502480408566774,
 0.19440590261983046,
 0.20030605630579307,
 0.2076278183927196,
 0.21641208569361967,
 0.21700891692688234,
 0.2302308326997715,
 0.3078066482948334}

In [20]:
df["Text_5"] = X.toarray().tolist()
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                                 [dogal, dil, isle]   
853  [ver, madencilik, doğal, dil, işle, uygulamas,...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                     dogal dil isle   
853  ver madencilik doğal dil işle uygulamas httpww...   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

In [21]:
len(X.toarray()[0])

5325

# Word2vec

In [22]:
pip install gensim

Note: you may need to restart the kernel to use updated packages.


In [23]:
from gensim.models import Word2Vec

In [24]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [25]:
model=Word2Vec(sentences =df["Text_2"].tolist(),vector_size=100, window=5, min_count=1)
model.save("data/word2vec.model")

In [26]:
print(model)

Word2Vec<vocab=5350, vector_size=100, alpha=0.025>


In [27]:
words=list(model.wv.index_to_key)
words[0:6]

['dil', 'doğal', 'işle', 'yapay', 'zeka', 'il']

In [28]:
len(words)

5350

In [29]:
df

Text   
0    Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1    🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2    Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3    9. Baidu Research: Çin'in önde gelen arama mot...   
4    4. Microsoft AI: Microsoft'un yapay zeka tekno...   
..                                                 ...   
851  doğal dil işleme alanında yüksek lisans-doktor...   
852                           dogal dil isleme şeyleri   
853  Bir veri madenciliği ve doğal dil işleme uygul...   
854  "Doğal dil işleme" ile ilgili deneyimi olan ya...   
855  Haftaya öğrencilik hayatıma kaldığım yerden de...   

                                                Text_2   
0    [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1    [veri, analiz, edin, chatgptyi, kullanarak, do...   
2    [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3    [baidu, research, çin, ön, gele, ara, motor, b...   
4    [microsoft, ai, microsoft, yapay, zeka, teknol...   
..                                                 ...   
851  [doğal, dil, işle, alan, yük, lisansdoktor, ya...   
852                                 [dogal, dil, isle]   
853  [ver, madencilik, doğal, dil, işle, uygulamas,...   
854  [doğal, dil, işleme, il, ilgil, deney, ola, ya...   
855  [hafta, öğrencilik, hayat, kaldık, yer, deva, ...   

                                                Text_3   
0    yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1    veri analiz edin chatgptyi kullanarak doğal di...   
2    öncelik yapay zeka olduğunu iç önemli olduk kı...   
3    baidu research çin ön gele ara motor baidun ar...   
4    microsoft ai microsoft yapay zeka teknoloji od...   
..                                                 ...   
851  doğal dil işle alan yük lisansdoktor yapa danı...   
852                                     dogal dil isle   
853  ver madencilik doğal dil işle uygulamas httpww...   
854  doğal dil işleme il ilgil deney ola yazılımcı ...   
855  hafta öğrencilik hayat kaldık yer deva ediyoru...   

                                                Text_4   
0    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4    [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
..                                                 ...   
851  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
852  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
853  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
854  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
855  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                                Text_5  
0    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4    [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
..                                                 ...  
851  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
852  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
853  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
854  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
855  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  

[856 rows x 5 columns]

In [30]:
model.wv.key_to_index["yapay"]


3

In [31]:
model.wv[3]

array([-0.01543091,  0.09737164,  0.04981393, -0.01694725,  0.075605  ,
       -0.21303803,  0.10131231,  0.3254031 , -0.12947   , -0.10306395,
       -0.02171904, -0.24970554,  0.00158755,  0.09736915,  0.02013147,
       -0.13911112,  0.06923783, -0.12031461, -0.04296447, -0.3348048 ,
        0.13122246,  0.03722759,  0.09564323, -0.07714901, -0.03201959,
       -0.01989079, -0.01768514, -0.06413472, -0.1061573 , -0.02502546,
        0.14925551, -0.03798259,  0.04403368, -0.1486004 , -0.07009289,
        0.13397834,  0.05896984, -0.13082784, -0.10044377, -0.25559536,
       -0.01601695, -0.17733729, -0.07245088,  0.03714645,  0.14912844,
       -0.03381651, -0.133241  , -0.07424074,  0.05623765,  0.06566221,
        0.05512341, -0.11799476, -0.14036363, -0.03123617, -0.05928159,
        0.03042602,  0.07361587, -0.00296396, -0.12924905,  0.07151861,
        0.02870401,  0.05299522,  0.06751087,  0.04401277, -0.16173233,
        0.15991156,  0.03446952,  0.08396015, -0.21077304,  0.17

In [32]:
model.wv.get_vector("yapay")

array([-0.01543091,  0.09737164,  0.04981393, -0.01694725,  0.075605  ,
       -0.21303803,  0.10131231,  0.3254031 , -0.12947   , -0.10306395,
       -0.02171904, -0.24970554,  0.00158755,  0.09736915,  0.02013147,
       -0.13911112,  0.06923783, -0.12031461, -0.04296447, -0.3348048 ,
        0.13122246,  0.03722759,  0.09564323, -0.07714901, -0.03201959,
       -0.01989079, -0.01768514, -0.06413472, -0.1061573 , -0.02502546,
        0.14925551, -0.03798259,  0.04403368, -0.1486004 , -0.07009289,
        0.13397834,  0.05896984, -0.13082784, -0.10044377, -0.25559536,
       -0.01601695, -0.17733729, -0.07245088,  0.03714645,  0.14912844,
       -0.03381651, -0.133241  , -0.07424074,  0.05623765,  0.06566221,
        0.05512341, -0.11799476, -0.14036363, -0.03123617, -0.05928159,
        0.03042602,  0.07361587, -0.00296396, -0.12924905,  0.07151861,
        0.02870401,  0.05299522,  0.06751087,  0.04401277, -0.16173233,
        0.15991156,  0.03446952,  0.08396015, -0.21077304,  0.17

In [33]:
def word2vec(value):
    model=Word2Vec.load("data/word2vec.model")
    bfr_list=[]
    bfr_len=len(value)

    for k in value:
        bfr=model.wv.key_to_index[k]
        bfr=model.wv[bfr]
        bfr_list.append(bfr)

    bfr_list=sum(bfr_list)
    bfr_list=bfr_list/bfr_len
    return bfr_list.tolist()


In [34]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5  
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...

In [39]:
df["Text_6"]=df["Text_2"].apply(word2vec)

In [41]:
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6   
0  [-0.005160877481102943, 0.04136011749505997, 0...  \
1  [-0.0021245700772851706, 0.03436165675520897, ...   
2  [-0.0031358685810118914, 0.04265280440449715, ...   
3  [-0.005224099848419428, 0.036406952887773514, ...   
4  [-0.0065759215503931046, 0.05138162150979042, ...   

                                                 bow   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               tfidf   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.005160877481102943, 0.04136011749505997, 0...  
1  [-0.0021245700772851706, 0.03436165675520897, ...  
2  [-0.0031358685810118914, 0.04265280440449715, ...  
3  [-0.005224099848419428, 0.036406952887773514, ...  
4  [-0.0065759215503931046, 0.05138162150979042, ...

In [37]:
df ["bow"] = on_islem.bag_of_words(df["Text_3"]) 
df ["tfidf"] = on_islem.tfidf(df["Text_3"])
df ["word2vec"]=df["Text_2"].apply (on_islem.word2vec)
df.head()

Text   
0  Yapay Zeka Nedir, Ne İşe Yarar?\n\nYapay zeka ...  \
1  🔎 Verilerinizi analiz edin: \nChatGPT'yi kulla...   
2  Öncelikle yapay zekanın ne olduğunu, #dijitala...   
3  9. Baidu Research: Çin'in önde gelen arama mot...   
4  4. Microsoft AI: Microsoft'un yapay zeka tekno...   

                                              Text_2   
0  [yapay, zeka, nedir, işe, yarar, yapay, zeka, ...  \
1  [veri, analiz, edin, chatgptyi, kullanarak, do...   
2  [öncelik, yapay, zeka, olduğunu, iç, önemli, o...   
3  [baidu, research, çin, ön, gele, ara, motor, b...   
4  [microsoft, ai, microsoft, yapay, zeka, teknol...   

                                              Text_3   
0  yapay zeka nedir işe yarar yapay zeka yz bilgi...  \
1  veri analiz edin chatgptyi kullanarak doğal di...   
2  öncelik yapay zeka olduğunu iç önemli olduk kı...   
3  baidu research çin ön gele ara motor baidun ar...   
4  microsoft ai microsoft yapay zeka teknoloji od...   

                                              Text_4   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                              Text_5   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                              Text_6   
0  [-0.005160877481102943, 0.04136011749505997, 0...  \
1  [-0.0021245700772851706, 0.03436165675520897, ...   
2  [-0.0031358685810118914, 0.04265280440449715, ...   
3  [-0.005224099848419428, 0.036406952887773514, ...   
4  [-0.0065759215503931046, 0.05138162150979042, ...   

                                                 bow   
0  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...  \
1  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
2  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
3  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   
4  [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, ...   

                                               tfidf   
0  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...  \
1  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
2  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
3  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   
4  [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, ...   

                                            word2vec  
0  [-0.005160877481102943, 0.04136011749505997, 0...  
1  [-0.0021245700772851706, 0.03436165675520897, ...  
2  [-0.0031358685810118914, 0.04265280440449715, ...  
3  [-0.005224099848419428, 0.036406952887773514, ...  
4  [-0.0065759215503931046, 0.05138162150979042, ...